/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/emergency`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/book` | `/book`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/welfare` | `/welfare`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/booking/[id]` | `/booking/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(worker)'}/job/[id]` | `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/emergency`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/book` | `/book`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/bookings` | `/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/services` | `/services`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/welfare` | `/welfare`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/booking/[id]` | `/booking/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(worker)'}/job/[id]` | `/job/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/emergency${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/book${`?${string}` | `#${string}` | ''}` | `/book${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/bookings${`?${string}` | `#${string}` | ''}` | `/bookings${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/services${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/welfare${`?${string}` | `#${string}` | ''}` | `/welfare${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/emergency`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/book` | `/book`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/welfare` | `/welfare`; params?: Router.UnknownInputParams; } | `${'/(customer)'}/booking/${Router.SingleRoutePart<T>}` | `/booking/${Router.SingleRoutePart<T>}` | `${'/(worker)'}/job/${Router.SingleRoutePart<T>}` | `/job/${Router.SingleRoutePart<T>}` | { pathname: `${'/(customer)'}/booking/[id]` | `/booking/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(worker)'}/job/[id]` | `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
